-- Inserir dados nas Tabelas Dimensão
USE ameacasglobaissegurancacibernetica;
INSERT INTO dim_country (country) VALUES ('Australia');
INSERT INTO dim_country (country) VALUES ('Brazil');
INSERT INTO dim_country (country) VALUES ('China');
INSERT INTO dim_country (country) VALUES ('France');
INSERT INTO dim_country (country) VALUES ('Germany');
INSERT INTO dim_country (country) VALUES ('India');
INSERT INTO dim_country (country) VALUES ('Japan');
INSERT INTO dim_country (country) VALUES ('Russia');
INSERT INTO dim_country (country) VALUES ('UK');
INSERT INTO dim_country (country) VALUES ('USA');
INSERT INTO dim_year (year) VALUES ('2015');
INSERT INTO dim_year (year) VALUES ('2016');
INSERT INTO dim_year (year) VALUES ('2017');
INSERT INTO dim_year (year) VALUES ('2018');
INSERT INTO dim_year (year) VALUES ('2019');
INSERT INTO dim_year (year) VALUES ('2020');
INSERT INTO dim_year (year) VALUES ('2021');
INSERT INTO dim_year (year) VALUES ('2022');
INSERT INTO dim_year (year) VALUES ('2023');
INSERT INTO dim_year (year) VALUES ('2024');
INSERT INTO dim_attack_type (attack_type) VALUES ('DDoS');
INSERT INTO dim_attack_type (attack_type) VALUES ('Malware');
INSERT INTO dim_attack_type (attack_type) VALUES ('Man-in-the-Middle');
INSERT INTO dim_attack_type (attack_type) VALUES ('Phishing');
INSERT INTO dim_attack_type (attack_type) VALUES ('Ransomware');
INSERT INTO dim_attack_type (attack_type) VALUES ('SQL Injection');
INSERT INTO dim_target_sector (target_sector) VALUES ('Banking');
INSERT INTO dim_target_sector (target_sector) VALUES ('Education');
INSERT INTO dim_target_sector (target_sector) VALUES ('Government');
INSERT INTO dim_target_sector (target_sector) VALUES ('Healthcare');
INSERT INTO dim_target_sector (target_sector) VALUES ('IT');
INSERT INTO dim_target_sector (target_sector) VALUES ('Retail');
INSERT INTO dim_target_sector (target_sector) VALUES ('Telecommunications');
INSERT INTO dim_attack_origin (attack_origin) VALUES ('Hacker Group');
INSERT INTO dim_attack_origin (attack_origin) VALUES ('Insider');
INSERT INTO dim_attack_origin (attack_origin) VALUES ('Nation-state');
INSERT INTO dim_attack_origin (attack_origin) VALUES ('Unknown');
INSERT INTO dim_vulnerability_type (vulnerability_type) VALUES ('Social Engineering');
INSERT INTO dim_vulnerability_type (vulnerability_type) VALUES ('Unpatched Software');
INSERT INTO dim_vulnerability_type (vulnerability_type) VALUES ('Weak Passwords');
INSERT INTO dim_vulnerability_type (vulnerability_type) VALUES ('Zero-day');
INSERT INTO dim_defense_mechanism (defense_mechanism) VALUES ('AI-based Detection');
INSERT INTO dim_defense_mechanism (defense_mechanism) VALUES ('Antivirus');
INSERT INTO dim_defense_mechanism (defense_mechanism) VALUES ('Encryption');
INSERT INTO dim_defense_mechanism (defense_mechanism) VALUES ('Firewall');
INSERT INTO dim_defense_mechanism (defense_mechanism) VALUES ('VPN');
